[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-proxy"
  status = 200
  force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200