[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/proxy/*"
  to = "https://kopis.or.kr/:splat"
  status = 200
  force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200